export default {
  "name": "config",
  "GLOBAL_CSS_VERSION": "20170606073143",
  "SSO_JS_VERSION": "20170606073143",
  "LIBRARY_JS_VERSION": "20170606073143",
  "EXTERNAL_JS_VERSION": "20170606073143",
  "SERVICE_CSS_VERSION": "20170606073143",
  "SERVICE_JS_VERSION": "20170606073143",
  "LOCAL_CSS_VERSION": "20170606073143",
  "LOCAL_JS_VERSION": "20170606073143",
  "IMA_DEST_DOMAIN": "http://s.motime.com/ima",
  "FLV_DEST_DOMAIN": "http://flv.buongiorno.com",
  "IMG_DEST_DOMAIN": "http://s.motime.com/img",
  "CSS_DEST_DOMAIN": "http://s.motime.com/css/",
  "JS_DEST_DOMAIN": "http://s.motime.com/js/",
  "PREVIEW_DEST_DOMAIN": "http://s.motime.com/p/",
  "ACQUISITION_GRAPHITE": 1,
  "ACQUISITION_GRAPHITE_ENV": "SITE",
  "ACQUISITION_GRAPHITE_UTS": 1,
  "ACQUISITION_GRAPHITE_UTS_TIME_THRESHOLD": 100,
  "ACQUISITION_GRAPHITE_UTS_KPI_1_ON_N": 10,
  "ACQUISITION_GRAPHITE_SELF_MONITOR": 1,
  "ACQUISITION_GRAPHITE_SELF_MONITOR_1_ON_N": 100,
  "ACQUISITION_GRAPHITE_SELF_MONITOR_TREE_NAME": "Acquisition.ww.graphite",
  "DN_FW_FILESCAN_CACHE": 300,
  "appId": "GENERIC_WEBAPP_B2",
  "SHOW_SEARCH": 1,
  "SHOW_PEOPLE": 1,
  "SHOW_BLOG": 1,
  "SHOW_VIDEO": 1,
  "SHOW_AUDIO": 0,
  "SHOW_IMAGE": 1,
  "SHOW_FORUM": 1,
  "SHOW_TAG": 1,
  "SHOW_CATEGORY": 1,
  "SHOW_COMMENT": 1,
  "SHOW_VOTE": 1,
  "SHOW_ALERTSMAIL": 1,
  "SHOW_NEWSLETTERSMS": 0,
  "SHOW_LINK_PS": 1,
  "NEWSSMS_MO_SUBSCRIBE": 0,
  "NEWSSMS_MO_DELETE": 0,
  "SHOW_OTHER_COUNTRIES": 1,
  "IP_CONTROL": 1,
  "NO_CAPTCHA": 0,
  "TERMS_CHECKED": 1,
  "HIDE_TERMS_CHECKED": 1,
  "SUBSCRIPTION_CHECK_PRIVACY": 1,
  "SUBSCRIPTION_CHECK_PERSONALDATA": 1,
  "CELLULAR_MODEL_TABLE": "model",
  "SHOW_DELETE_PROFILE": 1,
  "SHOW_FRIENDS_AFFILIATION": 0,
  "SHOW_SPOT_TEXT": 1,
  "SHOW_SPOT_BANNER_MINI": 0,
  "SHOW_SPOT_BANNER_HOME": 0,
  "NO_UPSELLING": "1",
  "SHOW_WAP_SPOT_ADSENSE": 1,
  "SHOW_WAP_SPOT_ADMOB": 1,
  "SHOW_MP3_FULL_TRACK": 1,
  "SHOW_MOBILE_TRACK": 1,
  "SHOW_RINGTONE_COVER": 1,
  "SHOW_PERSONALHOMEPAGE": "1",
  "SUBSCRIPTION_WORKFLOW": "8",
  "USE_FLASH_STORAGE_CHECK_ON_SUBSC": 1,
  "DNMEDIA_USE_API": 1,
  "USE_NEW_FORMATTER": 1,
  "USE_PREVIEW_XML_RESPONSE": "1",
  "SHOW_MULTIUPLOAD": 1,
  "ADSENSE_CODE": "pub-1692857587271504",
  "ADSENSE_CODE_HOST": "pub-1692857587271504",
  "ADSENSE_MAX_ACCOUNT": "3",
  "ADSENSE_WILDCARD": [
    "pub-1692857587271504"
  ],
  "ANALYTICS_CODE": "UA-110947-4",
  "ANALYTICS_CODE_SUBS": "UA-110947-5",
  "STORE_MEDIALIST_HOME": "mostvisited",
  "IS_TAB2_HOME_CHART": "1",
  "SHOW_ALBUM": 1,
  "SHOW_MULTIPLAYER": 1,
  "SPOT_BANNER_SITE": "DADAWWW",
  "SHOW_SPOT_VIDEOADS": 0,
  "SPOT_VIDEOADS_DISABLED": {
    "CATEGORY_30": 1
  },
  "SIMPLY_ID_728X90": "2470",
  "SIMPLY_ID_250X250": "2478",
  "SIMPLY_ID_300X250": "2479",
  "SIMPLY_ID_160X600": "2473",
  "SIMPLY_ID_728X90_2": "3667",
  "SITEMAP_MUSIC_PREFIX": 1,
  "STORE_HOME_EVENTS_NUMBER_LIST": 20,
  "STORE_HOME_PLAYLIST_NUMBER_LIST": 20,
  "STORE_GRID_NUM_ROWS": "6",
  "STORE_GRID_NUM_COLS": "4",
  "LIST_NUM_ELEMENT_STORE": "10",
  "LIST_NUM_ELEMENT_STORE_AJAX": "30",
  "GSEARCH_TAB_NUM_ELEMENT_STORE": "10",
  "GRID_NUM_ROWS": "8",
  "GRID_NUM_COLS": "6",
  "LIST_NUM_ELEMENT": "18",
  "STORE_HOME_EVENTS_ROLLER": "4",
  "STORE_HOME_PLAYLIST_ROLLER": "4",
  "USERS_RANK_LEVEL_1": "50",
  "USERS_RANK_LEVEL_2": "40",
  "USERS_RANK_LEVEL_3": "30",
  "NEW_HEAD": 1,
  "MUSICSTORE_DEFAULT_IDCLASS": 11,
  "flight_id_opzionale_mstore": "856,25689,0",
  "SITE4UTENTI": 3,
  "FIRST_YOUTUBE_VIDEO_ID": "10491283",
  "USE_SEARCH_ON_API": "1",
  "SEARCH_NUM_AUDIO": "50",
  "SEARCH_NUM_VIDEO": "24",
  "SEARCH_NUM_IMAGE": "24",
  "SEARCH_NUM_USER": "30",
  "SEARCH_NUM_ALBUM": "30",
  "SEARCH_NUM_PLAYLIST": "30",
  "USE_HOME_ON_API": "1",
  "USE_GS5": 0,
  "PLAYLIST_SEARCH": "1",
  "CS_AUDIO_COVER_PREVIEW_ENABLED": 1,
  "CS_AUDIO_PREVIEW_ENABLED": 1,
  "CS_IMAGE_PREVIEW_ENABLED": 1,
  "CS_VIDEO_PREVIEW_ENABLED": 1,
  "CS_ALBUM_PREVIEW_ENABLED": 1,
  "CS_APPLICATION_ANDROID_PREVIEW_ENABLED": 1,
  "USE_SPHINX_FOR_USER": "1",
  "USE_SPHINX_FOR_AUDIO": "1",
  "USE_SPHINX_FOR_ALBUM": "1",
  "FACEBOOK_LOGIN_XD_RECEIVER": "/sn_api/fb/xd_receiver.htm",
  "FACEBOOK_LOGIN_OFF_VER": "A5",
  "FACEBOOK_SUBSCRTIPTION_FLOW_TYPE": "fb_email_username",
  "TWITTER_LOGIN_OFF_VER": "A6",
  "TWITTER_LOGIN_SUBSCRIPTION_URL": "/auth/tw_connect/?",
  "SHOW_RECAPTCHA_FOR_SUPPORT": 1,
  "WURFL_AKAMAI_ENABLE": true,
  "SHOW_FORCE_EMAIL_TRIANG": "1",
  "LE_USE_MT": 1,
  "terms": "/platinum/#!/terms/terms",
  "SHOW_PARTNER_PIXEL": 1,
  "SHOW_GOOGLE_CHECKBOX_WEB": "1",
  "LEAFENGINE": 1,
  "LEAFENGINE_GEOIP": 0,
  "ACTIVE_SUBSCRIBER": 1,
  "COUNTRY_REGEXP_VALIDATE_PIN": "/^([0-9]{4})$/",
  "COUNTRY_REGEXP_VALIDATE_MSISDN": "/^(?:\\+39)?([0-9]{10})$/",
  "COUNTRY_REGEXP_VALIDATE_PLATINUM_PIN": "^([0-9]{4})$",
  "COUNTRY_REGEXP_VALIDATE_PLATINUM_MSISDN": "^(?:\\+39)?([0-9]{10})$",
  "ENABLE_CAT_API_TRACK": true,
  "ENABLE_UNIFIED_KPI_TRACK": true,
  "SITE_ENABLE_CATFILTERS": true,
  "MULTIPRODUCT_ENABLE": true,
  "USER20_METHODS": "cache,bridge,legacy,buser",
  "GOOGLE_TAG_ID": "GTM-P4FZGV",
  "DOTTED_SITENAME": "life.",
  "IS_WEB": true,
  "LEAF_ENGINE_DB": "1",
  "LEAF_ENGINE_UNKN_TRK_BEHAV": "fallback",
  "RPC_XML_URL": "/xmlrpc.php",
  "RPC_PARAMS": [],
  "EMAIL_DEST_DOMAIN": "email.dada.net",
  "CAT_DEFAULT_SUBSCRIBE_URL": "/subscribe/?cr={[CREATIVITY_ID]}",
  "HAS_APPUSER": 1,
  "GAIA_SERVICE_ID": 5,
  "DEPLOYED_PATH": "/opt/fe/lib/",
  "NOT_SHOW_BACK_HOME_AFTER_UNSUB": 0,
  "CAT_TRACKING_ENABLED": true,
  "BPLAYER_360DEFAULT_FORMAT": "vr480p",
  "BPLAYER_CSS_DOMAIN_devel": "d2.motime.com/css/",
  "BPLAYER_CSS_DOMAIN": "d.motime.com/css/",
  "BPLAYER_CSS_PREFIX": "wl/webstore_apps/",
  "BPLAYER_JS_DOMAIN_devel": "d2.motime.com/js/",
  "BPLAYER_JS_DOMAIN": "d.motime.com/js/",
  "BPLAYER_JS_PREFIX": "wl/webstore_apps/",
  "BPLAYER_OTASERVER_SERVICE_NAME": "imagazine",
  "BPLAYER_OTASERVER_ENDPOINT": "http://rest.cms.buongiorno.com/",
  "BPLAYER_OTASERVER_ENDPOINT_devel": "http://restpreprod.cms.buongiorno.com/",
  "BPLAYER_DEST_DOMAIN": false,
  "BPLAYER_URL_PATH": "bvideoplayer",
  "BPLAYER_URL_PATH_STREAMING": "bvideostreaming",
  "BPLAYER_ONMOBILE_ACCOUNT_ID": "4156526654001",
  "BPLAYER_ONMOBILE_PLAYER_ID": "BysdFCoU",
  "BPLAYER_ONMOBILE_API_KEY": "THsqd53DNOxafN4Laqa1MA",
  "ONMOBILE_ENDPOINT": "http://api.fonestarz.com",
  "VERSION_API_ONMOBILE": "v1-0-0",
  "EXT_REDING_URL": "http://reding.buongiorno.com",
  "EXT_REDING_URL_devel": "http://192.168.124.37:8000",
  "EXT_GAIA_URL": "http://mip-gaia.buongiorno.com",
  "EXT_GAIA_URL_devel": "http://192.168.124.37:8003",
  "EXT_LEADERBOARD_URL": "http://leaderboard.buongiorno.com",
  "EXT_LEADERBOARD_URL_devel": "http://192.168.124.37:8005",
  "S2S_CURL_COOKIES": [
    "developer",
    "dadaqa_test",
    "b_test_id",
    "disclaimer_seen"
  ],
  "BPLAYER_IMAGE_PREVIEW_SET": {
    "webpreview2": {
      "w": 1024,
      "h": 760,
      "resize_method": "cropin"
    },
    "cover_1200_800": {
      "w": 1200,
      "h": 800,
      "resize_method": "cropin"
    },
    "cover_1_4_1": {
      "w": 1120,
      "h": 800,
      "resize_method": "cropin"
    },
    "cover_2_1": {
      "w": 1200,
      "h": 600,
      "resize_method": "cropin"
    },
    "additionalwebpreview": false
  },
  ";BPLAYER_USE_IMAGE_PREVIEW": "cover_2_1",
  "BPLAYER_USE_IMAGE_PREVIEW": "webpreview2",
  "BPLAYER_IMAGE_RESIZER_BASEURL_devel": "http://s2.motime.com/l/images/abs/[WSIZE]x[HSIZE]/[METHOD]/mnt/alfresco_content_preprod/content/contentstore",
  "BPLAYER_IMAGE_RESIZER_BASEURL": "http://s.motime.com/l/images/abs/[WSIZE]x[HSIZE]/[METHOD]/mnt/alfresco_content_prod/contentstore",
  "BPLAYER_OTA_PREVIEWS_URL_TOCUT": "http://vs.be3a.com/cmsp",
  "BPLAYER_OTA_PREVIEWS_URL_TOCUT_devel": "http://vs.be3a.com/cmst",
  "URL_SHORTENER_PATH": "@",
  "FLOWPLAYER_KEY": "$140657326192374",
  "ERRORS_WITH_NATIVE_SUGGESTION": [
    998
  ],
  "SET_NT_VARS": true,
  "CAT_TRACKING_ENABLED_PAGES": [
    "index",
    "zoom",
    "gameplay",
    "url_zoom_wallpapers",
    "url_zoom_webapp_text",
    "url_zoom_fulltrack",
    "url_zoom_truetones",
    "url_zoom_voicetones",
    "url_zoom_sounds",
    "url_zoom_androidapplications",
    "url_zoom_video",
    "welcome_html"
  ],
  "CAT_PARAMS": {
    "MANDATORY": {
      "dest": "kpiName",
      "trackExecutionKey": "trackExecutionKey"
    },
    "OPTIONAL": []
  },
  "CAT_TRACK_COOKIE_NAME": "catalytics_track",
  "CAT_TRACKING_URL_devel": "http://cat2apistg.buongiorno.com/track",
  "CAT_TRACKING_URL": "http://cat2api.buongiorno.com/track",
  "TRACKINGPARAMS": [
    "utm_source",
    "utm_campaign",
    "utm_medium",
    "utm_content"
  ],
  "NEWTON_S2S_SECRET": "P7a)qsZyGLf5?e#JTEYg",
  "NEWTON_S2S_SECRET_devel": "!_slAWrbljSsS<Lv9NSA",
  "FORCE_REDIRECT_SUB_ERR_DEST": 1,
  "SERVICE_FOR_OTA": "gameasy",
  "USER_RECOGNITION_SETTINGS_STATUS": false,
  "SHOW_HELP_MIP_LOGIN": "1",
  "DO_NOT_ADD_ENDING_SLASH": 1,
  "DO_NOT_PREPEND_WITH_HASH": 1,
  "MOA_API_CONFUZE_VERSION": "v02",
  "LOG_TRACKER_PATH": "/tmp/LOGS/dadamobile2/logtracker/",
  "AJAX_GOOGLE_JQUERY": "http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/",
  "QR_CODE_BASEURL": "/qrcode/",
  "NOCACHEHOME": 1,
  "SHOW_ARTIST": 1,
  "LEAF_ENGINE_NEW": 1,
  "LEAF_ENGINE": "/sso/f/",
  "LEAF_ENGINE_URL": "/leafengine/",
  "LEAF_ENGINE_CONF_devel": {
    "IFRAME_OPENER_URL": "/sso/d/s.php",
    "COMMUNITY_DEFAULT_SUBSCRIBE_URL": "/error.php?error=999",
    "GENERAL_ERROR_URL": "/error.php?error=998",
    "LOGGED_USER_FORCE_REDIRECT_URL": "/",
    "ROOT_PATH": "/dadanet2/panelout2/leafengine/",
    "CONTENT_FORMATTER_OFF": "mobi"
  },
  "LEAF_ENGINE_CONF": {
    "IFRAME_OPENER_URL": "/sso/d/s.php",
    "COMMUNITY_DEFAULT_SUBSCRIBE_URL": "/error.php?error=999",
    "GENERAL_ERROR_URL": "/error.php?error=998",
    "LOGGED_USER_FORCE_REDIRECT_URL": "/",
    "ROOT_PATH": "/dadanet/panelout/leafengine/",
    "CONTENT_FORMATTER_OFF": "mobi"
  },
  "SHOW_DISCLAIMER_IMAGE": 1,
  "USE_IMG_DEST_DOMAIN_ON_SPOT": 1,
  "IMG_CACHE_KEY": false,
  "LEAF_ENGINE_TMPL_DIR_devel": "/dadanet2/panelout2/leafengine/tmpl",
  "LEAF_ENGINE_TMPL_DIR": "/dadanet/panelout/leafengine/tmpl",
  "SEARCH_ENGINE": "elasticsearch",
  "USE_WURFLER": 1,
  "VERIFY_FIXED_POSITION": 1,
  "TIMEOUT_REDIRECT_HOME": 5000,
  "LOSTPASSWORD_URL": "/lostpassword",
  "LESS_URL_devel": "http://s2.motime.com/tbr/less.css",
  "LESS_URL": "http://s.motime.com/tbr/less.css",
  "LESS_CACHE_PATH_devel": "/dadanet2/panelout2/less/cache/",
  "LESS_CACHE_PATH": "/dadanet/panelout/less/cache/",
  "LESS_IMG_URL": "http://s.motime.com/img/wl/webstore_",
  "LESS_IMG_URL_devel": "http://s2.motime.com/img/wl/webstore_",
  "LESS_FONT_URL": "http://s.motime.com/css/wl/webstore_",
  "LESS_FONT_URL_devel": "http://s2.motime.com/css/wl/webstore_",
  "LESS_FILENAME": "app.less",
  "CSS_PATH_devel": "/dadanet2/css2/htdocs/wl/webstore_",
  "CSS_PATH": "/dadanet/css/htdocs/wl/webstore_",
  "IMG_PATH_devel": "/dadanet2/img2/htdocs/wl/webstore_",
  "IMG_PATH": "/dadanet/img/htdocs/wl/webstore_",
  "JS_PATH_devel": "/dadanet2/js2/htdocs/wl/webstore_",
  "JS_PATH": "/dadanet/js/htdocs/wl/webstore_",
  "IMG_CONSTANTS_FILE": "constants_images.conf",
  "FONT_CONSTANTS_FILE": "constants_fonts.conf",
  "IMG_CONSTANTS_FILE_FOR_JS": "constants_images_for_js.conf",
  "ADD_IMAGES_TOCONFIG": false,
  "SHOW_ANIMATION_SWIFFY_WEB": 1,
  "SHOW_ANIMATION_WEB": 1,
  "JS_PREFIX_APPS": "js/wl/webstore_apps/",
  "JS_PREFIX": "wl/webstore_html5game/",
  "JS_MIP_PREFIX": "wl/webstore_apps/mip/",
  "JS_DEST_DOMAIN_devel": "http://s2.motime.com/js/",
  "JS_BUILD_DEST_DOMAIN_devel": "http://d2.motime.com/js/",
  "JS_BUILD_DEST_DOMAIN": "http://d.motime.com/js/",
  "JS_MIP_TY_PAGE_REDIRECT_TIMEOUT": "1500",
  "IMG_DEST_DOMAIN_devel": "http://s2.motime.com/img",
  "CSS_DEST_DOMAIN_devel": "http://s2.motime.com/css/",
  "MOA_API_DEST_DOMAIN_devel": "http://api2.motime.com/",
  "MOA_API_DEST_DOMAIN": "http://api.motime.com/",
  "PREVIEW_DEST_DOMAIN_devel": "http://s2.motime.com/p/",
  "LAPIS_DEST_DOMAIN": "http://resources.buongiorno.com/lapis/",
  "LAPIS_DEST_DOMAIN_devel": "http://resources2.buongiorno.com/lapis/",
  "LAPIS_STATIC_DOMAIN_devel": "http://s2.motime.com/l/",
  "LAPIS_STATIC_DOMAIN": "http://s.motime.com/l/",
  "QRCODE_URL_devel": "http://s2.motime.com/tbr/qrcode/",
  "QRCODE_URL": "http://s.motime.com/tbr/qrcode/",
  "QRCODE_ON_STATICS": 1,
  "MOA_API_REDING_END_POINT_devel": "http://192.168.124.37:8000",
  "MOA_API_REDING_END_POINT": "http://reding.buongiorno.com",
  "MOA_API_CONTENTS_END_POINT_devel": "http://192.168.124.37:8001",
  "MOA_API_CONTENTS_END_POINT": "http://contenz.buongiorno.com",
  "MOA_API_CATEGORIES_END_POINT_devel": "http://192.168.124.37:8001",
  "MOA_API_CATEGORIES_END_POINT": "http://contenz.buongiorno.com",
  "PRE_PREFIX_RATING": "rating-",
  "PRE_PREFIX_LABEL": "label-",
  "STARS_RATING": 5,
  "SITE_PLATINUM": 1,
  "SHOW_SOCIAL_WEB": 0,
  "MOA_API_VERSION": "v01",
  "MOA_API_CONTENZ_VERSION": "v02/contenz",
  "MOA_APIKEY": "abcdef1234567890",
  "PRIVACY_BLOCK_SAVE_USER_FLAG": false,
  "PAYMENT_ONLY_CONTENT_ERROR_CODE": "1403",
  "ERROR_DOWNLOAD_CODE": "1500",
  "ERROR_INTERNAL_TROUBLE": "1501",
  "ERROR_ITEM_NOT_FOUND": "1404",
  "ERROR_MIP_LOGIN": "2404",
  "ERROR_MIP_LOGIN_CONFIRMATION": "22401",
  "ERROR_MIP_SIGNUP": "2500",
  "ERROR_MIP_SIGNUP_FREMIUM": "2501",
  "ERROR_MIP_TOKEN": "2401",
  "ERROR_MIP_SITEACCESS": "2403",
  "ERROR_FACEBOOK_NO_INVITATION_FOUND": "3404",
  "ERROR_GAIA_USER_NOT_FOUND": "3405",
  "ERROR_MIP_HYBRID_ACCOUNT_ALREADY_USED": "4403",
  "MIPCONNECT_EMAIL_FROM_EMAIL": "noreply@buongiorno.com",
  "MIPCONNECT_EMAIL_FROM_NAME": "Gameasy",
  "MIPCONNECT_SHOW_PRIVACY_CLAIM": 1,
  "MIPCONNECT_SHOW_PRIVACY_LINK_OLDVERSION": 1,
  "MIPCONNECT_SHOW_PRIVACY_CLAIM_ONLOGIN": 1,
  "MIPCONNECT_SHOW_PRIVACY_CHECKBOX": 1,
  "MIPCONNECT_SHOW_PRIVACY_CHECKBOX_ONLOGIN": 1,
  "MIPCONNECT_SIGNUP_TRIANGULATION": 0,
  "MIPCONNECT_ALLOW_MIP_SIGNUP_WITHOUT_DADANETUSER": 0,
  "MIPCONNECT_SHOW_SKIP_DISCLAIMER": 1,
  "MIPCONNECT_CHANGEMAIL_SEND_COURTESY": false,
  "USER_PHOTO_PATH": "/WEBAPP/user/mip/",
  "PSK_AUTH": "jshfbhejrfreq",
  "DISABLE_CAPTCHA": true,
  "DISABLECSFR": true,
  "MIPCONNECT_SHOW_PRELOGIN": 0,
  "USE_RECOMMENDATION_ENGINE": false,
  "ALIAS_CHECK_URL": "http://wap.mobivillage.in/test/alias?msisdn=:MSISDN",
  "HAS_CATEGORY_IMAGES": false,
  "HAS_CATEGORY_URL_LEAF_ENGINE_SUBSCRIPTION": false,
  "APPS_FORMATS": {
    "androidapplications": 0,
    "all": 0,
    "html5applications": 1
  },
  "QR_CODE_JS": 1,
  "GAMEPLAY_TMPL_INCLUDES": [
    "inc/mip_thankyoupage.tmpl"
  ],
  "GAMEPLAY_JSDATA_DICTIONARY_KEYS": {
    "thankyoupage_on_mip_message_title": "MIP_THANKYOUPAGE_MESSAGE_TITLE",
    "thankyoupage_on_mip_message_body": "MIP_THANKYOUPAGE_MESSAGE_BODY",
    "thankyoupage_on_mip_message_title_alt": "MIP_THANKYOUPAGE_MESSAGE_TITLE_ALT",
    "thankyoupage_on_mip_message_subtitle_alt": "MIP_THANKYOUPAGE_MESSAGE_SUBTITLE_ALT",
    "thankyoupage_on_mip_message_button_alt": "MIP_THANKYOUPAGE_BUTTON_ALT",
    "thankyoupage_on_mip_message_body_alt": "MIP_THANKYOUPAGE_MESSAGE_BODY_ALT"
  },
  "IMAGES_FOR_CONFIG_JS": [
    "SPRITE_GAME_SVG",
    "SPRITE_GAME_PNG",
    "transparent-background",
    "default-avatar",
    "default_label",
    "loader",
    "GOOGLE_PLAY_STORE",
    "APPLE_PLAY_STORE"
  ],
  "APPEND_SLASH_TO_COMPOSE_URL": 1,
  "ENABLE_NEWTON_TRACKING": true,
  "NEWTON_VALUABLES_EVENTS": [],
  "PAYMETHOD_GWALLET_CONFIRMED_EMAIL": true,
  "STATICS_DOMAIN_devel": "http://s2.motime.com/html5statics/",
  "STATICS_DOMAIN": "http://s.motime.com/html5statics/",
  "STATICS_DOMAIN_SCRIPT": "http://s.motime.com/html5statics/script/",
  "STATICS_DOMAIN_SCRIPT_devel": "http://s2.motime.com/html5statics/script/",
  "ENABLE_HTML5STATICS_CHANGE": 1,
  "GAME_URL_LIST_TO_EXCLUDE": [
    "/ga_for_games.js"
  ],
  "IS_SINGLE_FORMAT": 1,
  "LAPIS_ENDPOINT": "http://resources.buongiorno.com/lapis/apps",
  "LAPIS_ENDPOINT_devel": "http://resources2.buongiorno.com/lapis/apps",
  "GAIA_ADD_NEWTON_TRACKING_S2S": true,
  "HASAPPUSER": 1,
  "USER_AUTH_SERVICES": {
    "auth_id": "AUTH_FB_GAIA",
    "gwallet_auth_id": "AUTH_GWALLET_GAIA",
    "itunes_auth_id": "AUTH_ITUNES_GAIA"
  },
  "NEWTON_SDK_VERSION": "v2.x",
  "JS_BUILD_URL": "http://d.motime.com/js/wl/webstore_gameasy/dist/",
  "JS_BUILD_URL_devel": "http://d2.motime.com/js/wl/webstore_gameasy/dist/",
  "LESS_IMG_DEPLOYED_URL": "http://d.motime.com/",
  "LESS_IMG_DEPLOYED_URL_devel": "http://d2.motime.com/",
  "APPSFLYER_ENABLED": 1,
  "APPSFLYER_INIT_EVENT": "CampaignAttribution",
  "APPSFLYER_PREFIX": "AF_",
  "APPSFLYER_FIELDS": [
    "media_source",
    "campaign"
  ],
  "HYBRID_INITIALIZE_EVENT": "InitializeApp",
  "SITE_ERROR_REDIRECT_TIMEOUT": false,
  "THANKYOUPAGE_ON_MIP": 0,
  "THANKYOUPAGE_ON_MIP_DELAY_MS": "5000",
  "SHOW_CHALLENGES_TAB": true,
  "SHOW_PRIVACY_BLOCK": true,
  "CSS_LOCAL_LOGIN": "http://s.motime.com/css/wl/webstore_gameasy/csslocallogin.css?ts=1",
  "CSS_LOCAL_LOGIN_devel": "http://s2.motime.com/css/wl/webstore_gameasy/csslocallogin.css?ts=1",
  "SERVICE_TITLE": "gameasy",
  "SHAREME_ENABLED": "true",
  "FACEBOOK_SHARE_ENABLED": true,
  "TWITTER_SHARE_ENABLED": true,
  "ERROR_JS_NOT_SUPPORTED_CODE": 1426,
  "GOOGLEPLUS_SHARE_ENABLED": true,
  "NEW_GAMIFIVE": true,
  "TRUE_KEY": true,
  "FALSE_KEY": false,
  ";SENTRY_URL": "http://6dda41e5a97e48edbe00eb1344220b1e@sentry2.appsfuel.com:9000/19",
  "LOGGER_ENABLED": true,
  "USE_CS_ID": false,
  "WELCOME_AS_HOME": 0,
  "HAS_AVATAR": 1,
  "HAS_MIPUSEREXTENDED": 1,
  "AVATAR_CACHE_KEY": "html5avatar",
  "ENABLE_OTACOMPATIBILITY_CHECK": 1,
  "ENABLE_DYNAMIC_FOOTER_LINK": 1,
  "TY_APK_DLD_TRACKING": 0,
  "SHOW_FOOTER": 1,
  "SHOW_TERMS_FOOTER": 1,
  "SHOW_SETTINGS_FOOTER": 1,
  "SHOW_STATUS_BOTH_FOOTER": 1,
  "SHOW_STATUS_UNLOGGED_FOOTER": 0,
  "SHOW_STATUS_LOGGED_FOOTER": 0,
  "SHOW_ABOUT_FOOTER": 0,
  "SHOW_SAVE_ICON_FOOTER": 0,
  "SHOW_SURVEY_FOOTER": 0,
  "SHOW_COMPATIBILITY_FOOTER": 0,
  "SHOW_SERVICE_FOOTER": 0,
  "SHOW_HELPDOC_FOOTER": 0,
  "SHOW_IMPRINT_FOOTER": 0,
  "SHOW_MIP_ACCOUNT_FOOTER": 0,
  "SHOW_AMAZON_ACCOUNT_FOOTER": 0,
  "SHOW_FACEBOOK_FOOTER": 0,
  ";SHOW_TEXT_HEADER": 0,
  ";SHOW_FOOTER_SERVICE_DESCRIPTION": 0,
  "SHOW_OG_TAGS": 1,
  "SHOW_OVER_HEADER_OPERATORS": [
    "vodafone.pt",
    "fake.pt"
  ],
  "POSITION_FOOTER_TERMS": 1,
  "POSITION_FOOTER_SETTINGS": 2,
  "POSITION_FOOTER_STATUS_BOTH": 3,
  "HOME_DIRECT_PLAY": true,
  "SHOW_BLOCK_FBSHARE": 1,
  "HTML5GAMEPLAY_DIR": "html5gameplay",
  "ENABLE_USER_FREEMIUM": true,
  "MAX_FREE_CONTENTS": 100,
  "AVAILABLE_FOR_GUEST": "1",
  "SHOW_PAGE_BEFORE_PAYWALL": true,
  "HIDE_IAP_CREDENTIALS": true,
  "ALLOW_IAP_3G": true,
  "MIP_LOGIN_TYPE": false,
  "ENABLE_POSTMESSAGE_IAP": true,
  "COOKIE_GUESTUSER_DATA": "guestdata",
  "SHOW_IAP_COMPLETE_PROFILE": true,
  "ENABLE_FB_CHALLENGE": false,
  "ENABLE_INTERNAL_CHALLENGE": true,
  "FREEMIUM_MAX_TIMES_USER_CAN_ADD": 0,
  "FREEMIUM_MAX_CREDITS_AT_TIME": 0,
  "FREEMIUM_MAX_INCREASE_CREDIT_POLICY": "one-for-invited",
  "FREEMIUM_MAX_CREDITS_USER_CAN_EARN": 0,
  "ACTIVITY_NOCONTENT_LABEL_SLUG": "welcome",
  "MOA_API_LEADERBOARD_END_POINT_devel": "http://192.168.124.37:8005",
  "MOA_API_LEADERBOARD_END_POINT": "http://leaderboard.buongiorno.com",
  "AUTODOWNLOAD_REDIRECT_PLAY_TIME": 1,
  "REDIRECT_PLAY_TIME_devel": 6000,
  "REDIRECT_PLAY_TIME": 60,
  "WELCOME_DOMAIN": false,
  "SHOW_FB_CONNECT": true,
  "MIPCONNECT_EMAIL_CONFIRMATION": true,
  "MIPCONNECT_EMAIL_CONFIRMATION_REDIRECT_TODESTINATION_BEFORE_CONFIRM": false,
  "SMARTLOGIN_TMPL": "appslogin",
  "SMARTFORGOT_TMPL": "appsforgot",
  "SHOW_FOOTER_STATUS": false,
  "SHOW_BANNER_FOOTER": true,
  "SHOW_STATUS_UNSUBSCRIBE_NOT_LOGGED_ALSO_LOGGED": 0,
  "CSS_PREFIX": "wl/webstore_html5game/",
  "IMG_PREFIX": "wl/webstore_it_gameasy/",
  "IMG_PREFIX_COMMON": "wl/webstore_gameasy/",
  "JS_DEST_DOMAIN_COMMON": "http://s.motime.com/js/",
  "JS_DEST_DOMAIN_COMMON_devel": "http://s2.motime.com/js/",
  "JS_PREFIX_COMMON": "wl/webstore_apps/",
  "SHOW_WELCOME_GHOST": false,
  "REGEXP_VALIDATE_EMAIL": ".+@.+\\..+",
  "REGEXP_VALIDATE_PASSWD": "\\S{6,10}",
  "ROUTER_HOME": "/",
  "ROUTER_LABEL": "/special/:labelName/:labelId",
  "ROUTER_CATEGORY": "/category/:categoryId/:categoryName",
  "ROUTER_FAVORITES": "/favorites",
  "ROUTER_GAME_URL": "/games/:gameURL",
  "ROUTER_SEARCH": "/search/:query",
  "ROUTER_SETTINGS": "/settings",
  "ROUTER_ABOUT": "/about",
  "ROUTER_FORGOT": "/forgot",
  "ROUTER_LOGIN": "/login",
  "ROUTER_SAVE": "/save",
  "ROUTER_STATUS": "/status",
  "ROUTER_TERMS": "/terms/:contentId",
  "ROUTER_ERROR": "/error{code:(?:/[0-9]+)?}",
  "ROUTER_TOPSCORES": "/topscores",
  "ROUTER_CHALLENGES": "/challenges",
  "ADD2HOME_POPUP": 0,
  "IMG_AVATAR_BIG_PATH": "/dadanet/img/htdocs/wl/webstore_html5game/images/avatar/big/",
  "IMG_AVATAR_BIG_PATH_devel": "/dadanet2/img2/htdocs/wl/webstore_html5game/images/avatar/big/",
  "IMG_AVATAR_URL": "http://s.motime.com/img/wl/webstore_html5game/images/avatar/big/",
  "IMG_AVATAR_URL_devel": "http://s2.motime.com/img/wl/webstore_html5game/images/avatar/big/",
  "TRACK_VIDEO_PLAY_HISTORY": false,
  "ANALYTICS_GA_UNIVERSAL": true,
  "GOOGLE_ANALYTICS_ID_UNIVERSAL": "UA-74338374-1",
  "WEBAPP_JS_ADD2HOME_POPUP": true,
  "PROFILE_EMAIL_SHOW": false,
  "PROFILE_MOBILE_SHOW": true,
  "PROFILE_FBCONNECT_SHOW": true,
  "SETTINGS_LOGIN_SHOW": true,
  "MIPUSER_SERVICE_PREFIX": "gamifive",
  "HAS_DOWNLOAD": 0,
  "HAS_GAMEPLAY_URL": 1,
  "ENABLE_FAVORITES": true,
  "ENABLE_DISLIKE": true,
  "UTM_TRACKING": true,
  "NEWTON_APPID": "gamifive",
  "NEWTON_SECRETID_devel": "f$xC_L3RwY&h8kraC&!o",
  "NEWTON_SECRETID": "P$iCNLBRpY&h8RrUCe![",
  "NEWTON_URL": "https://client-api.newton.pm",
  "GFSDK_VERSION": "3.x.x",
  "SDK_URL_devel": "http://d2.motime.com/js/wl/webstore_html5game/gfsdk/2.x.x/dist/gfsdk.js",
  "SDK_URL": "http://d.motime.com/js/wl/webstore_html5game/gfsdk/2.x.x/dist/gfsdk.min.js",
  "SDK_SAVED_CONF": {
    "dictionaryKeys": [
      "WEBAPP_CONGRATULATIONS_SCORE",
      "WEBAPP_YOUR_POSITION_TITLE",
      "WEBAPP_CANVAS_BUTTON_PLAY",
      "WEBAPP_RELATED_TITLE",
      "PLAY",
      "WEBAPP_GAMEOVER_GUEST_FAVS",
      "WEBAPP_GAMEOVER_GUEST_FAVS_SIGNIN",
      "WEBAPP_HYBRIDINSTALL_TXT",
      "WEBAPP_HYBRIDINSTALL_APPINFO",
      "WEBAPP_HYBRIDINSTALL_APPINFOSMALL",
      "WEBAPP_BANNER_BUTTON",
      "WEBAPP_CHALLENGE_INVITE",
      "WEBAPP_SHARE_FACEBOOK"
    ],
    "vhostKeys": [
      "SHOW_INGAME_ADS",
      "CONTENT_RANKING",
      "SPRITE_GAME_SVG",
      "SPRITE_GAME_PNG",
      "MOA_API_APPLICATION_OBJECTS_GET",
      "MOA_API_APPLICATION_OBJECTS_SET",
      "NEWTON_SECRETID",
      "TLD",
      "NT_REAL_COUNTRY",
      "INSTALL_HYBRID_VISIBLE"
    ]
  },
  "UNIFY_FOOTER_BEHAVIOR": 1,
  "TEST_ALE": false,
  "GOOGLE_TAG_ENABLE": false,
  "GAMEOVER_LIKE_SELECTOR": "span#heartIcon",
  "GAMEOVER_LIKE_CLASS_TO_TOGGLE": "ico-red",
  "NEWTON_APPLICATION_OBJECTS": [
    {
      "class_name": "gameInfo",
      "fields": {
        "contentId": {
          "type": "String",
          "mandatory": true,
          "isNull": false
        },
        "info": {
          "type": "Binary",
          "mandatory": true,
          "isNull": false
        },
        "note": {
          "type": "Binary",
          "mandatory": false,
          "isNull": true
        },
        "domain": {
          "type": "String",
          "mandatory": true,
          "isNull": false
        }
      }
    }
  ],
  "SHOW_MULTIPLE_LANGUAGE": 0,
  "FB_SCOPE": "public_profile,user_friends,email",
  "HYBRID_CONF": "%7B%22IAP%22%3A%7B%22id%22%3A%22kradio_hybrid_subscription%22%2C%22alias%22%3A%22Premium%22%2C%22type%22%3A%22PAID_SUBSCRIPTION%22%2C%22verbosity%22%3A%22DEBUG%22%2C%22paymethod%22%3A%22gwallet%22%7D%7D",
  "HYBRID_APISELECTOR": "kradio",
  "DISABLE_NEWTON_TRACKING": false,
  "INSTALL_HYBRID_VISIBLE": true,
  "HYBRID_INSTALL_SHOW_INTERVAL": 1,
  "MFP_COOKIE_LIST": "dadanetuser,info_utente,mipuser",
  "MFP_API_URL": "http://api.motime.com/v01/mobileFingerprint.",
  "MFP_API_URL_devel": "http://api2.motime.com/v01/mobileFingerprint.",
  "MFP_EXPIRE": "600",
  "MOTIME_API_KEY": "556a42415047494483",
  "USE_APPUSER_IN_DOCUMENTS": true,
  "GOOGLE_ANALYTICS_DOMAINS": [
    "gamifive.mobivillage.com.au",
    "gamifive.mobivillage.in",
    "www.gamifive.com.my",
    "www.gamifive.com.sg",
    "gamifive.mobivillage.fr",
    "www.gamifive.nl",
    "www.gamifive.be",
    "www.game-in.es",
    "gamifive.mobivillage.es",
    "www.taptofun.es",
    "vip.taptofun.es",
    "gamifive.mobivillage.com.pt",
    "www.giochissimo.it",
    "www.gamifive.gr",
    "gamifivemp.mobivillage.com.tr",
    "gamifive.mobivillage.com.tr",
    "www.gamifive.com.ar",
    "www.gamifive.cl",
    "gamifive.mobivillage.com.mx",
    "gamifive.mobivillage.com.br",
    "www.gamifive.de",
    "bgames.itouchservice.de",
    "www.bgamesapp.co.uk",
    "www.gamifive.ch",
    "www.taptofun.ch",
    "www.gamifive.ru",
    "www.gamifive.co.za",
    "www.gamifive.ae"
  ],
  "DESKTOP_FORMATS": {
    "all": 0,
    "androidapplications": 0,
    "html5applications": 1
  },
  "ANDROID_FORMATS": {
    "all": 0,
    "androidapplications": 0,
    "html5applications": 1
  },
  "SITEMAP_CONF": {
    "api_domain": "api.motime.com",
    "http_api_domain": "DEST_DOMAIN",
    "item_list": "v01/contents/?offset=[OFFSET]&size=[SIZE]&country=it",
    "category_list": "v01/categories/?offset=[OFFSET]&size=[SIZE]",
    "relative_url_item": 1,
    "relative_url_category": 1,
    "add_format": 1,
    "input_param_name_format": "formats",
    "allowed_formats": {
      "androidapplications": 0,
      "screensavers": 0,
      "wpnameanimated": 0,
      "flashanimations": 0,
      "fulltrack": 0,
      "html5applications": 1,
      "icontent": 0,
      "javaapplications": 0,
      "nametone": 0,
      "ringtones": 0,
      "ringbacktone": 0,
      "sounds": 0,
      "symbian": 0,
      "theme": 0,
      "truetones": 0,
      "video": 0,
      "voicetones": 0,
      "wallpapers": 0,
      "wpname": 0
    },
    "loc": {
      "default": "",
      "news": "url_leaf_engine_subscription",
      "cat": "url_category",
      "author": "",
      "artist": "",
      "tags": ""
    },
    "changefreq": {
      "default": "daily",
      "news": "weekly",
      "cat": "weekly",
      "label": "weekly"
    },
    "priority": {
      "default": "1.00",
      "news": "0.80",
      "cat": "0.80",
      "label": "0.80"
    }
  },
  "RANDOM_NICKNAME": [
    "roger",
    "tom",
    "peter",
    "john",
    "melissa",
    "kevin",
    "kate",
    "emily",
    "carol",
    "michael",
    "william",
    "david",
    "jan",
    "paul",
    "richard",
    "jennifer",
    "robert",
    "janice",
    "andrew",
    "robin"
  ],
  "DISPATCHING_OLD_TERMS": [
    "imprint",
    "terms",
    "info",
    "privacy",
    "service",
    "helpdoc",
    "compatibility"
  ],
  "APK_WRAPPER_URLS": {
    "unlogged_url": "<DEST_DOMAIN>subscribe?cr=<WRAPPER_CR>&type=w&wrapper=1",
    "loggedfree_url": "<DEST_DOMAIN>subscribe?cr=<WRAPPER_CR>&type=w&wrapper=1",
    "subscribed_url": "http://billing.wrapper.pool2.prod.mobivillage.com/gameasy/v1.0/subscriber/loginPage"
  },
  "HEADERS_DYNAMIC_JS": [
    "HEADER_JS_GAMEPLAY_UTILS",
    "HEADER_JS_STARGATE",
    "HEADER_JS_NEWTON_ADAPTER",
    "HEADER_JS_NEWTON_SDK"
  ],
  "CONTENT_RANKING": {
    "Page": {
      "game-page": {
        "guest": 1,
        "free": 3,
        "premium": {
          "natural": 5,
          "acquisition": 5
        }
      }
    },
    "Hybrid": {
      "OfflineToggleOn": {
        "guest": 0,
        "free": 0,
        "premium": {
          "natural": 15,
          "acquisition": 15
        }
      },
      "OfflineToggleOff": {
        "guest": 0,
        "free": 0,
        "premium": {
          "natural": -1,
          "acquisition": -1
        }
      }
    },
    "Play": {
      "GameLoad": {
        "guest": 3,
        "free": 7,
        "premium": {
          "natural": 10,
          "acquisition": 3
        }
      },
      "GameStart": {
        "guest": 5,
        "free": 10,
        "premium": {
          "natural": 15,
          "acquisition": 15
        }
      },
      "GameEnd": {
        "guest": 10,
        "free": 20,
        "premium": {
          "natural": 30,
          "acquisition": 30
        }
      },
      "DownloadAPK": {
        "guest": 3,
        "free": 7,
        "premium": {
          "natural": 10,
          "acquisition": 3
        }
      },
      "PlayClick": {
        "guest": 1,
        "free": 3,
        "premium": {
          "natural": 5,
          "acquisition": 5
        }
      },
      "PlayClickFromSlider": {
        "guest": 1,
        "free": 3,
        "premium": {
          "natural": 5,
          "acquisition": 5
        }
      }
    },
    "Favorites": {
      "Remove": {
        "guest": 0,
        "free": -5,
        "premium": {
          "natural": -10,
          "acquisition": -10
        }
      },
      "Add": {
        "guest": 0,
        "free": 5,
        "premium": {
          "natural": 10,
          "acquisition": 10
        }
      }
    },
    "Share": {
      "Common": {
        "guest": 5,
        "free": 10,
        "premium": {
          "natural": 15,
          "acquisition": 15
        }
      },
      "FbScore": {
        "guest": 10,
        "free": 20,
        "premium": {
          "natural": 30,
          "acquisition": 30
        }
      }
    }
  },
  "LOGSTASH_ADDRESS_devel": "192.168.124.143:%d",
  "LOGSTASH_ADDRESS_qa": "192.168.130.139:%d",
  "LOGSTASH_ADDRESS": "10.1.23.245:%d",
  "LOGSTASH_PORTS_devel": "9999-9999",
  "LOGSTASH_PORTS_qa": "9999-9999",
  "LOGSTASH_PORTS": "9901-9906",
  "BRIDGE_ENDPOINT_devel": "http://bridge.buongiorno.com/",
  "BRIDGE_END_POINT_devel": "http://bridge.buongiorno.com/",
  "BRIDGE_ENDPOINT": "http://bridge.buongiorno.com/",
  "BRIDGE_END_POINT": "http://bridge.buongiorno.com/",
  "REM_BRIDGE_ENDPOINT_INFO": "Not a typo, we have 2 almost identical variables",
  "SITE_COMPONENTS": {
    "remove": [
      "simplelogin:simplelogin",
      "simplelogin:login",
      "simplelogin:autologin",
      "unsubscribe_errors",
      "disclaimer"
    ]
  },
  "SITE_PHONE_HEADERS": {
    "AKAMAI_EDGE_IP": "AKAMAI_EDGE_IP",
    "cid": true,
    "HTTP_CARRIER": true,
    "HTTP_COOKIE": true,
    "HTTP_HOST": "X-Forwarded-Host",
    "HTTP_MSISDN": "MSISDN",
    "HTTP_SM_MS_CRYPTED": "HTTP_SM_MS_CRYPTED",
    "HTTP_USER_IDENTIFY_FORWARD_MSISDN": true,
    "HTTP_USER_IDENTITY_FORWARD_MSISDN": true,
    "HTTP_VIA": true,
    "HTTP_X_ALIAS": true,
    "HTTP_X_MSISDN": true,
    "HTTP_X_NOKIA_ALIAS": true,
    "HTTP_X_NOKIA_GID": true,
    "HTTP_X_NOKIA_MSISDN": true,
    "HTTP_X_NOKIA_TA_MSISDN": true,
    "HTTP_X_OPERATOR_DOMAIN": true,
    "HTTP_X_REAL_PORT": "REMOTE_PORT",
    "HTTP_X_UP_CALLING_LINE_ID": true,
    "HTTP_X_UP_CH_MSISDN": true,
    "HTTP_X_UP_FORWARDED_FOR": true,
    "HTTP_X_UP_SUBNO": true,
    "HTTP_X_VF_ACR": true,
    "HTTP_X_VC_ACR": true,
    "pagosvodafone": true,
    "REMOTE_ADDR": "REMOTE_ADDR",
    "REMOTE_PORT": "REMOTE_PORT",
    "X_NOKIA_ALIAS": true,
    "HTTP_MNO1": true,
    "HTTP_MNO2": true,
    "HTTP_MNO3": true,
    "HTTP_SM_NW_OPID": "sm_nw_opid",
    "sm_nw_opid": "sm_nw_opid",
    "HTTP_TM_USER_ID": "tm_user-id",
    "HTTP_X_RADIUS_1": true,
    "HTTP_X_RADIUS_2": true,
    "HTTP_X_MSID": true,
    "HTTP_X_WAP_MSISDN": "x-wap-msisdn"
  },
  "SITE_TIMEOUT": 20,
  "SITE_CUSTOMIZATIONS": {
    "LOGSTASH": {
      "*": true
    },
    "LOGFILE": {
      "*": false
    },
    "LOGBRIDGE": {
      "*": true
    },
    "LOGBRIDGE_devel": {
      "*": true
    },
    "LOGBRIDGE_qa": {
      "*": false
    },
    "REDIRECT_ON_ERROR": {
      "es": true
    },
    "BRUTEFORCE_TIMEOUT": {
      "*": 3
    },
    "BRUTEFORCE_TIMEOUT_qa": {
      "*": false
    },
    "BRUTEFORCE_TIMEOUT_devel": {
      "*": false
    },
    "ON_PORTAL": {
      "es_taptofun": true,
      "es_viptaptofun": true,
      "es_taptostar": true,
      "es_clubsexy": true,
      "es_todohumormovistar": true,
      "es_movisexysoft": true,
      "es_movisexyhard": true,
      "es_muyzorrasmovi": true,
      "es_worldsex": true,
      "es_fashiontv": true,
      "es_gameshaker": true,
      "es_sexvideos": true,
      "es_znacktv": true,
      "es_chefbook": true,
      "es_itrip": true,
      "es_mtopvideo": true,
      "es_gamedroid": true,
      "es_funplanet": true,
      "es_pocoyohouseemocion": true,
      "es_astrofuturo": true,
      "es_edukidz": true,
      "es_dailydiva": true
    },
    "loginsuffix": {
      "pt": "|msisdn",
      "sg": "|msisdn"
    },
    "siteasync": {
      "mx": true,
      "in": true,
      "br": true
    },
    "landing_siteasync": {
      "it": true,
      "br": true
    },
    "msisdn_priority": {
      "za": "input",
      ";ru": "input",
      "br": "input"
    },
    "freecountry": {
      "vn": [
        "vn",
        "it",
        ""
      ],
      "br": [
        "br",
        "it",
        "es",
        "",
        "ar",
        "cl",
        "mx",
        "uk",
        "pt"
      ]
    },
    "enable_fake_login": {
      "it": true,
      "in": true,
      "mx": true,
      "cl": true,
      "br": true,
      "ar": true,
      "za": true
    },
    "newton_notify": {
      "*": true
    },
    "newton_notify_devel": {
      "*": false
    },
    "override_expire": {
      "ru": 2592000,
      "es_pocoyohouse": 900,
      "es_pocoyohouseemocion": 900,
      "za_gameasy": 86400,
      "*": false
    }
  },
  "SITE_OPERATOR_CUSTOMIZATIONS": {
    "pinless": {
      "sprint.us": true,
      "verizon.us": true,
      "pt": true,
      "ar": true,
      "mx": true,
      "movistar.es": true,
      "celcom.my": true,
      "br_contatudoapp": true
    }
  },
  "LOGIN_MSISDN_VALIDATION": true,
  "FORCE_STATUS_LINK": true,
  "CATEGORIES_LOGIN_ENABLED": true,
  "SHOW_STATUS_BOTH": true,
  "SHOW_STATUS_LOGGED": false,
  "SITE_GRAPHITE": true,
  "SHOW_STATUS_UNLOGGED": false,
  "SITE_VERSION": 2,
  "WRAPPER_URL": "http://billing.wrapper.pool2.prod.mobivillage.com/gameasy/v1.0/subscriber/landingPage",
  "LOGROTATE": {
    "siteaccess2": 15
  },
  "IS_GAMEASY": 1,
  "ANDROIDAPPLICATIONS_NUM_ATTEMPTS": 10,
  "SHOW_ERROR_DESCRIPTION": 1,
  "SHOW_SITEMAP_LINK": 1,
  "SHOW_PRIVACY": true,
  "SHOW_TERMS": true,
  "SHOW_BLOGWORD_FOOTER": true,
  "POSITION_BLOGWORD": "4",
  "TWITTER_CARD_CONTENT": "summary_large_image",
  "GAME_START_LEADERBOARD": true,
  "DEBUG_USERFLOW_devel": 1,
  "DEBUG_USERFLOW": 0,
  "SA_PROD_LOG_devel": true,
  "SA_PROD_LOG": false,
  "CONTEXTUAL_DEST_DOMAIN": true,
  "FORWARD_REQUEST_URI_ON_URL_LEAF_ENGINE": 1,
  "REMOVE_COUNTRY_FROM_REQUEST_URI": 1,
  "FORCE_CUSTOMER_ID": "xx_gameasy",
  "HAS_BINARY_DOWNLOAD": true,
  "ROBOTS_NOINDEX": false,
  "ALLOWED_GAMEPLAY_FORMATS": [
    "html5applications",
    "androidapplications"
  ],
  "API_SWITCH_TO_LAPIS": "1",
  "MAX_GUEST_CONTENTS": 10,
  "SHOW_GAME_ACTIVITY": false,
  "AUTH_FB_GAIA": "66",
  "AUTH_GWALLET_GAIA": "67",
  "AUTH_ITUNES_GAIA": "68",
  "SHOW_FOOTER_SERVICE_DESCRIPTION_BELOW": 0,
  "FB_APPID": "1530616587235761",
  "FB_APPSECRET": "37f1c44dbafb8aab08160ffe8efc3262",
  "FB_USEMAINDESTDOMAIN": true,
  "MAIN_DEST_DOMAIN_devel": "http://www2.gameasy.com/",
  "MAIN_DEST_DOMAIN": "http://www.gameasy.com/",
  "STATIC_DEST_DOMAIN_devel": "http://s2.motime.com/",
  "STATIC_DEST_DOMAIN": "http://s.motime.com/",
  "CATEGORY_FILTER_OPTS": "guest,free,premium",
  "ANDROID_PREMIUM_FULLCATALOG_KEY": "destinatario",
  "ANDROID_PREMIUM_FULLCATALOG_ENABLED": true,
  "ROUTER_EXPLORE": "/explore",
  "ROUTER_HISTORY": "/history",
  "ROUTER_DOWNLOADED": "/downloaded",
  "ACTIVITY_CHALLENGE": false,
  "ACTIVITY_TOPSCORES": false,
  "ACTIVITY_FAVOURITES": true,
  "ACTIVITY_DOWNLOADED": true,
  "REM_MIPCONNECT_SHOW_PRIVACY_CLAIM": false,
  "ACTIVITY_HISTORY": true,
  "OFFLINE_MINIMUM_ACCESS": "premium",
  "HAS_CRITICAL_LESS": true,
  "SHOW_ACCESSTYPE_TOPSLIDER": false,
  "SHOW_EMPTY_STATES": false,
  "SHOW_INGAME_ADS": 0,
  "SHOW_INPAGE_ADS": "1",
  "SHOW_WEBAPP_ADS": "1",
  "SHOW_WEBAPP_ADS_MOBILE_ONLY": 1,
  "AD_IFRAME_URL": "/bannerads",
  "AD_CLIENT": "ca-pub-8608548322608076",
  "HOMEPAGECTR_TOP_ADV": "5314243626",
  "HOMEPAGECTR_BOTTOM_ADV": "2221176429",
  "GAMEPAGECTR_TOP_ADV": "6651376023",
  "GAMEPAGECTR_BOTTOM_ADV": "8128109223",
  "EXPLORECTR_TOP_ADV": "2081575625",
  "EXPLORECTR_BOTTOM_ADV": "3558308826",
  "LABELPAGECTR_TOP_ADV": "2081575625",
  "LABELPAGECTR_MIDDLE_ADV": "3558308826",
  "LABELPAGECTR_BOTTOM_ADV": "3558308826",
  "CATEGORYPAGECTR_TOP_ADV": "2081575625",
  "CATEGORYPAGECTR_MIDDLE_ADV": "3558308826",
  "CATEGORYPAGECTR_BOTTOM_ADV": "3558308826",
  "ACCESS_TYPE_RULES": {
    "guest": {
      "guest": {
        "dictKey": "WEBAPP_GAMEACCESS_GUEST",
        "class": "guest"
      },
      "free": {
        "dictKey": "WEBAPP_GAMEACCESS_FREE",
        "class": "free"
      },
      "premium": {
        "dictKey": "",
        "class": "hideBadge"
      }
    },
    "free": {
      "guest": {
        "dictKey": "WEBAPP_GAMEACCESS_GUEST",
        "class": "guest"
      },
      "free": {
        "dictKey": "WEBAPP_GAMEACCESS_GUEST",
        "class": "guest"
      },
      "premium": {
        "dictKey": "",
        "class": "hideBadge"
      }
    },
    "premium": {
      "guest": {
        "dictKey": "",
        "class": "hideBadge"
      },
      "free": {
        "dictKey": "",
        "class": "hideBadge"
      },
      "premium": {
        "dictKey": "",
        "class": "hideBadge"
      }
    }
  },
  "MFP_ENABLE": true,
  "MFP_AUTOLOGIN_ENABLE": true,
  "SHOW_NATIVE_APPS_LINKS": true,
  "GOOGLEPLAY_STORE_URL_HTTP": "https://app.appsflyer.com/com.docomodigital.gameasy.ww?pid=Webapp&c=<page>&af_sub1=<af_sub1>",
  "GOOGLEPLAY_STORE_URL": "https://app.appsflyer.com/com.docomodigital.gameasy.ww?pid=Webapp&c=<page>&af_sub1=<af_sub1>",
  "ITUNES_STORE_URL": "",
  "INSTALL_HYBRID_MIDPAGE_VISIBLE": true,
  "APPSFLYER_AUTOLOGIN": 1,
  "FB_USER_PIC_URL": "https://graph.facebook.com/{FACEBOOKID}/picture?type=square&height=100&width=100‌",
  "NEWTON_S2S_APPID_devel": "www2.gameasy.com",
  "NEWTON_S2S_APPID": "www.gameasy.com",
  "SHOW_PAGE_BEFORE_PAYWALL_WEB": false,
  "HYBRID_IAP_ID_ANDROID": "gameasy.ww.subscription.12012017.monthly",
  "HYBRID_IAP_ID_IOS": "gameasy.ww.subscription.12012017.monthly",
  "HYBRID_IAP_ALIAS": "Gameasy monthly subscription",
  "HYBRID_IAP_TYPE": "PAID_SUBSCRIPTION",
  "HYBRID_GAME_API_devel": "http://resources2.buongiorno.com/lapis/apps/contents.getList",
  "HYBRID_GAME_API": "http://resources.buongiorno.com/lapis/apps/contents.getList",
  "HYBRID_GAME_BUNDLELIST": [
    "7329ebbdf49065552dac00f4f6e1be10",
    "fd9ac2e5c1aeba0b89270688569d8f6e",
    "4cf74f31e3cf4f75d33d191b78639a57"
  ],
  "HYBRID_GAME_GA4G_devel": "http://www2.gameasy.com/ga_for_games.js",
  "HYBRID_GAME_GA4G": "http://www.gameasy.com/ga_for_games.js",
  "HYBRID_GAME_G5INFO_devel": "http://www2.gameasy.com/v01/gameplay_proxy",
  "HYBRID_GAME_G5INFO": "http://www.gameasy.com/v01/gameplay_proxy",
  "ENABLE_SG_PUSH": true,
  "SG_PUSH_INTERVAL": "259200000",
  "SHOW_STATIC_LOGIN_FORM": true,
  "AUTODOWNLOAD_PARAMS": [
    "dest",
    "trackExecutionKey"
  ],
  "SHOW_DLD_TIP_TIMER": 7000,
  "SHOW_SHAREBUTTONS": true,
  "SOCIALNETWORKS": [
    {
      "name": "facebook",
      "shareUrl": "https://www.facebook.com/dialog/share?app_id={app_id}&display=page&href={url}&redirect_uri={redirect_url}",
      "visible": true
    },
    {
      "name": "twitter",
      "shareUrl": "https://twitter.com/share?url={url}&text={title}",
      "visible": true
    },
    {
      "name": "google",
      "shareUrl": "https://plus.google.com/share?url={url}",
      "visible": true
    }
  ],
  "ADD_COUNTRY_TO_COM": true,
  "ENABLE_BLACKLIST": true,
  "BLACKLIST_ANDROID": "",
  "BLACKLIST_IOS": "",
  "NEW_DICTIONARY_REDIRECT": 1,
  "DICTIONARY_HYBRID_KEY": [
    "SEO_WEBAPP_HEAD_TITLE_TOP",
    "WEBAPP_HYBRIDINSTALL_TXT",
    "WEBAPP_HYBRIDINSTALL_APPINFO",
    "WEBAPP_HYBRIDINSTALL_APPINFOSMALL",
    "STATUS_UNSUBSCRIBE_NOT_LOGGED",
    "WEBAPP_PAYWALL_PURCHASE_TEXT",
    "STATUS_UNSUBSCRIBE_TEXT_WEBAPP"
  ],
  "REM_RANDOM_NICKNAME": [],
  "DEFAULT_TO_EMPTY_NICKNAME": true,
  "APK_WRAPPER_URLS_devel": {
    "unlogged_url": "<DEST_DOMAIN>subscribe?cr=<WRAPPER_CR>&setpreprod=1&type=w&settrack=gameasywrappertest&wrapper=1",
    "loggedfree_url": "<DEST_DOMAIN>subscribe?cr=<WRAPPER_CR>&setpreprod=1&type=w&settrack=gameasywrappertest&wrapper=1",
    "subscribed_url": "http://billing.wrapper.pool2.stg.mobivillage.com/gameasy/v1.0/subscriber/loginPage"
  },
  "REAL_CUSTOMER_ID": "xx_gameasy",
  "API_COUNTRY": "it-gameasy",
  "SHOW_CANCEL_BUTTON": "1",
  "SHOW_INFO_COST": true,
  "SHOW_COMPATIBILITY": true,
  "UNSUBSCRIPTION_MO": 0,
  "USER_ACCOUNT_subscription_profile_sms": 0,
  "DEST_DOMAIN": "http://www.gameasy.com/it/",
  "DEST_DOMAIN_devel": "http://www2.gameasy.com/it/",
  "TERMS_TEXT_PATH": "/dadanet/terms/dati/docs/it_gameasy/",
  "TERMS_TEXT_PATH_devel": "/dadanet2/terms2/dati/docs/it_gameasy/",
  "LIST_CONFIG_PATHS": {
    "scheduled_items_store": "/dadanet/rss/htdocs/musicstore/spot/webstore_it_gameasy/",
    "scheduled_items_spot": "/dadanet/rss/htdocs/musicstore/spot/webstore_it_gameasy/"
  },
  "LIST_CONFIG_PATHS_devel": {
    "scheduled_items_store": "/dadanet2/rss2/htdocs/musicstore/spot/it_it_gameasy/",
    "scheduled_items_spot": "/dadanet2/rss2/htdocs/musicstore/spot/it_it_gameasy/"
  },
  "APK_PREFIX": "wl/webstore_it_gameasy/apk/",
  "APK_NAME": "it_gameasy",
  "WIDGET_APP_NAME": "gameasy",
  "AUTODOWNLOAD_AFTER_SUB": true,
  "SHOW_DLD_TIP": true,
  "SITE_PROFILE": "games",
  "SITE_SERVICE": "gameasy",
  "WRAPPER_CR": "78644",
  "EASYREPLICA_CREATED": "2017-02-24 10:16:09",
  "EASYREPLICA_CREATED_FROM": "federico.dafrassini",
  "FAKE": "",
  "IS_HTML5": true,
  "IS_SMARTPHONE": true,
  "IS_TABLET": 0,
  "IS_ENABLE_FIXED_POSITION": true,
  "IS_WIRELESS_DEVICE": 1,
  "IS_OPERA": false,
  "IS_OPERA_EXTREME_MODE": false,
  "DEVICE_OS": "Android",
  "OS_VERSION": "5.0",
  "UA": "ANDROID",
  "ACTIVE_FORMAT": "html5applications",
  "ALLOWED_FORMATS": {
    "html5applications": {
      "baseurl": "html5applications"
    }
  },
  "SHOW_QR": 1,
  "QR_CODE_TEXT": "http%3A%2F%2Fwww.gameasy.com%2Fit%2F",
  "HEADER_JS_GAMEPLAY_UTILS": "http://s.motime.com/js/wl/webstore_apps/gameplay_utils.js",
  "HEADER_JS_STARGATE": "http://s.motime.com/js/wl/webstore_apps/stargate/stable/stargate.js",
  "HEADER_JS_NEWTON_ADAPTER": "http://s.motime.com/js/wl/webstore_apps/newton-adapter-v1.0.1.js",
  "HEADER_JS_NEWTON_SDK": "//static.newton.pm/js/v2.x/newton.min.js",
  "DIXIE_URL": "http://s.motime.com/tbr/dixie.js?country=it-gameasy",
  "MOA_API_CONTENT_HISTORY": "http://www.gameasy.com/it/v02/confuze/content-history:it_gameasy/%s/list/",
  "MOA_API_VOTE": "http://www.gameasy.com/it/v01/leaderboard/it_gameasy::ID/user/?service=5&newapps=1",
  "MOA_API_RATING": "http://www.gameasy.com/it/v01/rating/:ID/?prefix=rating-it_gameasy&newapps=1&get_details=:DETAILS",
  "MOA_API_CONTENTS_OLD": "http://www.gameasy.com/it/v01/contents/:ID?formats=:FORMATS&sort=-born_date&category=:CATEGORY&publisher=:PUBLISHER&size=:SIZE&offset=:OFFSET&label=:LABEL&label_slug=:LABEL_SLUG",
  "MOA_API_CONTENTS": "http://resources.buongiorno.com/lapis/apps/contents.getList?content_id=:ID&formats=:FORMATS&sort=-born_date&category=:CATEGORY&publisher=:PUBLISHER&size=:SIZE&offset=:OFFSET&label=:LABEL&label_slug=:LABEL_SLUG&access_type=:ACCESS_TYPE&real_customer_id=xx_gameasy&lang=it&use_cs_id=&white_label=it_gameasy&main_domain=http://www.gameasy.com/it/&country=it&fw=gameasy&vh=it.www.gameasy.com&check_compatibility_header=:CHECK_OTA&bl=:BLACKLIST&user_type=:USER_TYPE",
  "MOA_API_CONTENTS_PUSH": "http://resources.buongiorno.com/lapis/apps/contents.getList?content_id=:ID&formats=:FORMATS&sort=:SORT&size=:SIZE&offset=:OFFSET&label=:LABEL&label_slug=:LABEL_SLUG&access_type=:ACCESS_TYPE&real_customer_id=xx_gameasy&lang=it&use_cs_id=&white_label=it_gameasy&main_domain=http://www.gameasy.com/it/&country=it&fw=gameasy&vh=it.www.gameasy.com&check_compatibility_header=:CHECK_OTA&bl=:BLACKLIST&user_type=:USER_TYPE",
  "MOA_API_APPLICATION_OBJECTS_GET": "http://resources.buongiorno.com/lapis/apps/application-object.get?external_token=:EXTERNAL_TOKEN&access_token=:ACCESS_TOKEN&collection=:COLLECTION&id=:ID&query=:QUERY&white_label=it_gameasy&fw=gameasy&vh=it.www.gameasy.com",
  "MOA_API_APPLICATION_OBJECTS_SET": "http://resources.buongiorno.com/lapis/apps/application-object.set?external_token=:EXTERNAL_TOKEN&access_token=:ACCESS_TOKEN&collection=:COLLECTION&id=:ID&white_label=it_gameasy&fw=gameasy&vh=it.www.gameasy.com",
  "MOA_API_MYAPPS": "http://www.gameasy.com/it/v01/myapps/:ID?formats=:FORMATS",
  "MOA_API_CONTENTS_PLAYLIST_VIDEO": "http://www.gameasy.com/it/v01/contents/:ID?formats=:FORMATS&sort=:SORT&category=:CATEGORY&publisher=:PUBLISHER&size=:SIZE&offset=:OFFSET&label=:LABEL&fields=:FIELDS",
  "MOA_API_CATEGORIES": "http://resources.buongiorno.com/lapis/apps/categories.getList?real_customer_id=xx_gameasy&id=:ID&lang=it&formats=:FORMATS&sort=:SORT&size=:SIZE&offset=:OFFSET&white_label=it_gameasy&main_domain=http://www.gameasy.com/it/&fw=gameasy&vh=it.www.gameasy.com&sort=meta.it.name",
  "MOA_API_SEARCH": "http://resources.buongiorno.com/lapis/apps/contents.getList?q=:QUERY&content_id=:ID&formats=:FORMATS&category=:CATEGORY&size=:SIZE&offset=:OFFSET&real_customer_id=xx_gameasy&lang=it&use_cs_id=&white_label=it_gameasy&main_domain=http://www.gameasy.com/it/&country=it&fw=gameasy&vh=it.www.gameasy.com&check_compatibility_header=:CHECK_OTA&bl=:BLACKLIST&user_type=:USER_TYPE",
  "MOA_API_RELATED": "http://resources.buongiorno.com/lapis/apps/contents.getList?get_related=1&content_id=:ID&formats=:FORMATS&category=:CATEGORY&size=:SIZE&offset=:OFFSET&real_customer_id=xx_gameasy&lang=it&use_cs_id=&white_label=it_gameasy&main_domain=http://www.gameasy.com/it/&country=it&fw=gameasy&vh=it.www.gameasy.com&check_compatibility_header=:CHECK_OTA&bl=:BLACKLIST&user_type=:USER_TYPE",
  "MOA_API_LABELS": "http://www.gameasy.com/it/v01/activelabels/:ID?sort=:SORT&offset=:OFFSET",
  "MOA_API_DOWNLOAD": "http://www.gameasy.com/it/v01/contents/:ID/download?formats=:FORMATS",
  "MOA_API_ANALYTICS_ID": "http://www.gameasy.com/it/v01/session/:ID/?newapps=1",
  "MOA_API_USER_OPTIONSUPDATE": "http://www.gameasy.com/it/v01/user.optionsupdate?apikey=abcdef1234567890&country=it-gameasy",
  "MOA_API_MIP_USER_PROFILE_GET": "http://www.gameasy.com/it/v01/mipuser.getextra",
  "MOA_API_MIP_USER_PROFILE_UPDATE": "http://www.gameasy.com/it/v01/mipuser.updatedatauser",
  "MOA_API_MIP_USER_PROFILE_UPLOAD_IMAGE": "http://www.gameasy.com/it/v01/mipuser.uploadimg",
  "MOA_API_MIP_USER_FBDISCONNECT": "http://www.gameasy.com/it/v01/mipuser.fbdisconnect",
  "MOA_API_MIP_USER_DELETE": "http://www.gameasy.com/it/v01/mipuser.delete",
  "MOA_API_MIP_USER_PROFILE_RESET": "http://www.gameasy.com/it/v01/mipuser.resetprofile",
  "MOA_API_MIP_CREATEHYBRIDUSER": "http://www.gameasy.com/it/v01/mipuser.createhybriduser",
  "MOA_API_MIP_USER_MIPLOGIN": "http://www.gameasy.com/it/v01/mipuser.miplogin",
  "MOA_API_USER_CHANGE_EMAIL": "http://www.gameasy.com/it/v01/mipuser.changemail",
  "MOA_API_CREATEPONY": "http://www.gameasy.com/it/v01/createpony",
  "MOA_API_FAVORITES_GET": "http://www.gameasy.com/it/v01/favorites.get?apikey=abcdef1234567890",
  "MOA_API_FAVORITES_DELETE": "http://www.gameasy.com/it/v01/favorites.delete?apikey=abcdef1234567890",
  "MOA_API_FAVORITES_SET": "http://www.gameasy.com/it/v01/favorites.set?apikey=abcdef1234567890",
  "MOA_API_USER_TOP_SCORE": "http://www.gameasy.com/it/v01/mytopscore?apikey=abcdef1234567890",
  "MOA_API_USER_HISTORY": "http://www.gameasy.com/it/v01/myhistory",
  "MOA_API_USER_CHALLENGES_GET": "http://www.gameasy.com/it/v01/challenge.get?apikey=abcdef1234567890&type=:TYPE&size=:SIZE&offset=:OFFSET",
  "MOA_API_SMART_SECTION": "http://www.gameasy.com/it/v01/section.smart?apikey=abcdef1234567890&country=it-gameasy&subsection=:SUBSECTION&content_id=:CONTENT_ID&hybrid=:HYBRID",
  "MOA_API_USER_RECOGNIZE": "http://www.gameasy.com/it/v01/user.recognize?apikey=abcdef1234567890&country=it-gameasy",
  "MOA_API_USER_CHECK": "http://www.gameasy.com/it/v01/user.check?apikey=abcdef1234567890&country=it-gameasy&content_id=:CONTENT_ID&hybrid=:HYBRID&ts=:TS",
  "MOA_API_SPOTS": "http://www.gameasy.com/it/v01/spots/?formats=:FORMATS&medialist=:MEDIALIST",
  "MOA_API_SPOT_BANNER_LIST": "http://www.gameasy.com/it/v01/spot_banner/?formats=:FORMATS&medialist=:MEDIALIST",
  "MOA_API_RECOMMEND_EVENT": "http://www.gameasy.com/it/mip-ingestion/v01/recommend/event/:EVENT?customer_id=it_gameasy&user_id=:USERID&session=:SESSION&content_id=:CONTENT&rate=:RATING&referer=:REFER",
  "MOA_API_LIKE_ITEM": "http://www.gameasy.com/it/v02/reding/objects/:ID/users/:USER_ID/?prefix=FAV-it_gameasy",
  "MOA_API_LIKE_ITEM_USERS": "http://www.gameasy.com/it/v02/reding/objects/:ID/?prefix=FAV-it_gameasy",
  "MOA_API_LIKE_USER_ITEMS": "http://www.gameasy.com/it/v02/reding/users/:USER_ID/?prefix=FAV-it_gameasy",
  "categories": "#!/categories",
  "URLMGR_CATEGORIES-LINK": "#!/categories",
  "channels": "",
  "URLMGR_CHANNELS-LINK": "",
  "search": "#!/search",
  "URLMGR_SEARCH-LINK": "#!/search",
  "URLMGR_TERMS-LINK": "/platinum/#!/terms/terms",
  "settings": "/#!/settings",
  "URLMGR_SETTINGS-LINK": "/#!/settings",
  "login": "/it/platinum/#!/login",
  "URLMGR_LOGIN-LINK": "/it/platinum/#!/login",
  "old_login": "#!/login",
  "URLMGR_LOGIN": "#!/login",
  "about": "/#!/about",
  "URLMGR_ABOUT-LINK": "/#!/about",
  "status": "/subscribe_status",
  "URLMGR_STATUS-LINK": "/subscribe_status",
  "infos": "/#!/terms/costs",
  "URLMGR_INFO-LINK": "/#!/terms/costs",
  "privacy": "/#!/terms/privacy",
  "URLMGR_PRIVACY-LINK": "/#!/terms/privacy",
  "promo": "#!/promo",
  "URLMGR_PROMO-LINK": "#!/promo",
  "save": "/#!/save",
  "URLMGR_SAVE-LINK": "/#!/save",
  "web_account": "/web/account/",
  "URLMGR_WEB-ACCOUNT-LINK": "/web/account/",
  "web_faq": "/web/faq/",
  "URLMGR_WEB-FAQ-LINK": "/web/faq/",
  "web_about": "/web/about/",
  "URLMGR_WEB-ABOUT-LINK": "/web/about/",
  "web_terms": "/web/terms/",
  "URLMGR_WEB-TERMS-LINK": "/web/terms/",
  "web_infos": "/web/info/",
  "URLMGR_WEB-INFO-LINK": "/web/info/",
  "web_privacy": "/web/privacy/",
  "URLMGR_WEB-PRIVACY-LINK": "/web/privacy/",
  "static_error": "/error?error=",
  "URLMGR_STATIC-ERROR": "/error?error=",
  "apps_hits": "#!/special/androidapplications/top",
  "URLMGR_HITS-LINK": "#!/special/androidapplications/top",
  "apps_last": "#!/special/androidapplications/new",
  "URLMGR_LAST-LINK": "#!/special/androidapplications/new",
  "apps_mostview": "#!/viewed",
  "URLMGR_MOSTVIEWED-LINK": "#!/viewed",
  "forgot": "/it/platinum/#!/forgot",
  "URLMGR_FORGOT-LINK": "/it/platinum/#!/forgot",
  "lostpassword": "/it/lostpassword",
  "URLMGR_LOSTPASSWORD_URL": "/it/lostpassword",
  "act": "/siteleave?_PONY=12-a564aab4ea5a082435de87f725d57644999999END",
  "URLMGR_ACTION_URL": "/siteleave?_PONY=12-a564aab4ea5a082435de87f725d57644999999END",
  "mip_login": "#!/settings",
  "URLMGR_MIP-LOGIN-LINK": "#!/settings",
  "mip_signup": "/mip/signup",
  "URLMGR_MIP-SIGNUP-LINK": "/mip/signup",
  "mip_register": "/mip/register",
  "URLMGR_MIP-REGISTER-LINK": "/mip/register",
  "mip_reset": "/mip/reset",
  "URLMGR_MIP-RESET-LINK": "/mip/reset",
  "mip_doreset": "/mip/doreset",
  "URLMGR_MIP-DORESET-LINK": "/mip/doreset",
  "mip_toc_agree": "/mip/tocagree",
  "URLMGR_MIP-TOCAGREE-LINK": "/mip/tocagree",
  "mip_facebook_login": "/mip/fblogin?gotofblogin=1",
  "URLMGR_MIP-FBLOGIN-LINK": "/mip/fblogin?gotofblogin=1",
  "mip_connect": "/mip/connect",
  "URLMGR_MIP-CONNECT-LINK": "/mip/connect",
  "mip_changemail": "/mip/changemail",
  "URLMGR_MIP-CHANGE-EMAIL-LINK": "/mip/changemail",
  "mip_changepassword": "/mip/changepassword",
  "URLMGR_MIP-CHANGEPASSWORD-LINK": "/mip/changepassword",
  "mip_checknewmail": "mip/checknewmail",
  "URLMGR_MIP-CHECK-NEWMAIL-LINK": "mip/checknewmail",
  "mip_changedemailsucces": "mip/changedemailsucces",
  "URLMGR_MIP-CHANGED-EMAIL-SUCCESS-LINK": "mip/changedemailsucces",
  "mip_skip_mipconnect": "/mip/skipmipconnect",
  "URLMGR_MIP-SKIP-MIPCONNECT-LINK": "/mip/skipmipconnect",
  "myapps": "/subscribe_status/myapps",
  "URLMGR_MYAPPS-LINK": "/subscribe_status/myapps",
  "mip_profile": "/mip/profile",
  "URLMGR_MIP-PROFILE-LINK": "/mip/profile",
  "URLMGR_MIP-FBDISCONNECT-LINK": "/mip/profile",
  "mip_logout": "/mip/logout",
  "URLMGR_MIP-LOGOUT-LINK": "/mip/logout",
  "subscribe": "/subscribe",
  "URLMGR_SUBSCRIBE": "/subscribe",
  "URLMGR_SITEMAP": "http://www.gameasy.com/it/sitemap-it-index.xml",
  "LANGUAGE": "it",
  "INTERNATIONAL_PREFIX": "+39",
  "TLD": "it",
  "REAL_COUNTRY": "it",
  "WHITE_LABEL": "it_gameasy",
  "FW_TYPE": "gameasy",
  "SPRITE_GAME_SVG": "http://d.motime.com/gameasy/img/images/gameover/sprite.svg?v=20170606073143",
  "SPRITE_GAME_PNG": "http://d.motime.com/gameasy/img/images/gameover/sprite.png?v=20170606073143",
  "transparent-background": "http://d.motime.com/gameasy/img/images/transparent-bg.png?v=20170606073143",
  "default-avatar": "http://d.motime.com/gameasy/img/images/default-avatar.png?v=20170606073143",
  "default_label": "http://d.motime.com/gameasy/img/images/default_label.png?v=20170606073143",
  "loader": "http://d.motime.com/gameasy/img/images/ring.svg?v=20170606073143",
  "GOOGLE_PLAY_STORE": "http://d.motime.com/gameasy/img/images/google-play-store.png?v=20170606073143",
  "APPLE_PLAY_STORE": "http://d.motime.com/gameasy/img/images/apple-app-store.svg?v=20170606073143",
  "IS_ANDROID": 1,
  "nocacheatall": ""
}